### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by huijunchen9260** [jorsn/matlab-nix-imperative#1]
Hi! I am very new to NixOS, and I need matlab to be installed in my computer. I found this github page promising. May I ask if I have R2019b, how could I install using this software? I kept encountering problems that I don't know how to deal with:

```sh
[huijunchen@HJC ~/HJCRicing/nixos/matlab-nix-imperative]$ ./matlab                                                      ~/HJCRicing/nixos/matlab-nix-imperative
MATLAB: detail/MvmLocalBoundMethods.cpp:114: static void mvm::detail::MvmLocalBoundMethods::initMethods(bool): Assertion `Failed to open local mvm library: libgfortran.so.3: cannot open shared object file: No such file or directory' failed.
zsh: abort (core dumped)  ./matlab
```

**Comment by jorsn** [comment]
Hi! Great if this can be of use to you! You may also have a look at this discourse thread: <https://discourse.nixos.org/t/installing-matlab-on-nixos/8943>.

Now to your problem:
I last tested the script with R2019a. Before starting `./matlab`, you must install it. This nix expression does not do that, and it cannot easily since you must decide which components/toolboxes you want to install. These should be the required steps:

1. Enter a nix shell (run `nix-shell`) where all tthe dependencies are available.
2. Download and `unzip` the installer file.
3. Enter the directory you `unzip`ped to and run `./install` there.

Matlab should install normally. 
Does this work for you? If it does, you can either run matlab from the nix shell, or leave the shell and start matlab using the wrapper `./matlab`. If it does not work, please let me know.

**Comment by huijunchen9260** [comment]
The java environment started...WHY LOL
Why I type `nix-shell` in the `git clone` of the project, and suddenly I can open the installation window?!?!

That's amazing!

Does it mean that everytime I want to start matlab, I need to go to the directory with `default.nix` (or this github repository?) and type `nix-shell`, and then start matlab?

**Comment by jorsn** [comment]
> The java environment started...WHY LOL
> Why I type `nix-shell` in the `git clone` of the project, and suddenly I can open the installation window?!?!
> 
> That's amazing!

That's part of what makes nix so amazing: Define your local development environment in a `shell.nix`, type `nix-shell` and you're there.

> Does it mean that everytime I want to start matlab, I need to go to the directory with `default.nix` (or this github repository?) and type `nix-shell`, and then start matlab?

In principle, yes, but the wrapper `./matlab` does that for you (if you have installed matlab). To use, first follow the installation and configuration instructions in the README.

Notice one bug: Shell job control seems to not work properly with the wrapper script: If I remember correctly, if I start matlab with it and kill its parent shell, matlab does not close. This leads to a bit strange behavior for headless matlab, but you can always safely terminate it using e.g. `pkill` or manually enter the nix shell and start matlab in the first place. I didn't invest the time to debug this.

**Comment by huijunchen9260** [comment]
> That's part of what makes nix so amazing: Define your local development environment in a `shell.nix`, type `nix-shell` and you're there.

This is really cool. Does it mean that if I can understand nix's logic, I can just create an development environment without really install anything?

Also, like this project, do I really need to install jre for matlab to run? Or the `default.nix` already handled that for me?


> Notice one bug: Shell job control seems to not work properly with the wrapper script: If I remember correctly, if I start matlab with it and kill its parent shell, matlab does not close. This leads to a bit strange behavior for headless matlab, but you can always safely terminate it using e.g. `pkill` or manually enter the nix shell and start matlab in the first place. I didn't invest the time to debug this.

For some unknown reason, this bug doesn't happen on my computer. If I start the GUI of matlab from the wrapper, the parent shell terminal window just become an ordinary window which executing the external GUI program. If I close the terminal window, matlab GUI also disappeared. I really like this!

Some part that I've noticed is that if I run `matlab &`, nothing happened. It seems that `nix-shell` has to be in the foreground for it to work. Is my observation correct? Or there is another really for `matlab &` not be able to run correctly?

**Comment by jorsn** [comment]
> > That's part of what makes nix so amazing: Define your local development environment in a `shell.nix`, type `nix-shell` and you're there.
> 
> This is really cool. Does it mean that if I can understand nix's logic, I can just create an development environment without really install anything?

Partly: You don't install it into your environment. Nix installs it into the Nix store and makes the paths available to the nix-shell environment. If you garbage collect the store, the files are removed. There are methods for preventing cleanup of long-lived development environments, e.g. the experimental(!) flakes, some nix settings or lorri.

For Matlab, Nix even creates an FHS environment, which is an environment where everything is in the place where it would be on a normal linux system. This involves some chroot, and it is necessary for many proprietary programs because they expect files to be in certain locations.

> Also, like this project, do I really need to install jre for matlab to run? Or the `default.nix` already handled that for me?

`default.nix` handles it for you. Please have a look at it, if you haven't had already.

> Some part that I've noticed is that if I run `matlab &`, nothing happened. It seems that `nix-shell` has to be in the foreground for it to work. Is my observation correct? Or there is another really for `matlab &` not be able to run correctly?

Probably it is approximately for that reason. I remember I noticed some behavior like this as well. Nix shell doesn't always have to be in the foreground, but it might have to do with the way the nix shell is called and maybe also matlab. This is not a polished solution, but it was quickly written, is relatively simple and it works.

**Comment by huijunchen9260** [comment]
> Partly: You don't install it into your environment. Nix installs it into the Nix store and makes the paths available to the nix-shell environment. If you garbage collect the store, the files are removed. There are methods for preventing cleanup of long-lived development environments, e.g. the experimental(!) flakes, some nix settings or lorri.

That's amazing.

> For Matlab, Nix even creates an FHS environment, which is an environment where everything is in the place where it would be on a normal linux system. This involves some chroot, and it is necessary for many proprietary programs because they expect files to be in certain locations.

How does it possible? Like, which part in the `default.nix` is doing this job?

> 
> `default.nix` handles it for you. Please have a look at it, if you haven't had already.
> 

I read it, but don't understand lol. Do you recommend any good resource for understand Nix language / environment management?

> 
> Probably it is approximately for that reason. I remember I noticed some behavior like this as well. Nix shell doesn't always have to be in the foreground, but it might have to do with the way the nix shell is called and maybe also matlab. This is not a polished solution, but it was quickly written, is relatively simple and it works.

It just works. That's already good enough!

**Comment by huijunchen9260** [comment]
May I ask you questions that is not related to this project here?

The whole description is here:

https://www.reddit.com/r/NixOS/comments/jzwh64/cannot_connect_to_hdmi_on_thinkpad_p70/

Basically, I cannot get xrandr to detect any interface other than eDP1. However, using another drive with manjaro installed, it can detect.
